{
 "title": "NATS Watcher",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Watcher",
    "query": {
     "query": "label_values(nats_watch_gossip_received_delay_sum,name)"
    }
   },
   { "name": "expected_servers", "query": "9" }
  ]
 },
 "panels": [
  {
   "title": "Gossip Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nats_watch_gossip_received_delay_sum[1m]) \n/\nrate(nats_watch_gossip_received_delay_count[1m]) ",
     "legendFormat": "{{sender}} -> {{name}}"
    }
   ]
  },
  {
   "title": "NATS Server Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nats_watch_statsz_server_response_delay_sum[1m]) \n/\nrate(nats_watch_statsz_server_response_delay_count[1m]) ",
     "legendFormat": "{{server}} -> {{name}}"
    }
   ]
  },
  { "title": "Overview and Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "NATS Watcher Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "${name} Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "name",
   "collapsed": true,
   "panels": [
    {
     "title": "Server Pings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_watch_statsz_server_response_count{name=~\"${name}\"}[1m])*60",
       "legendFormat": "{{server}} -> {{name}}"
      },
      {
       "expr": "rate(nats_watch_statsz_requests_count{name=~\"${name}\"}[1m])*60",
       "legendFormat": "{{name}} Requests"
      }
     ]
    },
    {
     "title": "Gossip delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nats_watch_gossip_received_delay_sum{name=~\"$name\"}[1m]) \n/\nrate(nats_watch_gossip_received_delay_count{name=~\"$name\"}[1m]) ",
       "legendFormat": "{{name}} -> {{sender}}"
      },
      {
       "expr": "rate(nats_watch_gossip_received_delay_sum{sender=~\"$name\"}[1m]) \n/\nrate(nats_watch_gossip_received_delay_count{sender=~\"$name\"}[1m]) ",
       "legendFormat": "{{sender}} <- {{name}}"
      },
      {
       "expr": "sum(rate(nats_watch_gossip_received_delay_count{name=~\"$name\"}[5m]) )",
       "legendFormat": "Messages Received"
      }
     ]
    },
    {
     "title": "Server Response Delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nats_watch_statsz_server_response_delay_sum{name=~\"$name\"}[1m]) \n/\nrate(nats_watch_statsz_server_response_delay_count{name=~\"$name\"}[1m]) ",
       "legendFormat": "{{server}} ({{cluster}})"
      }
     ]
    },
    {
     "title": "Available Servers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "count(increase(nats_watch_statsz_server_response_count{name=\"${name}\"}[1m])>0) by (cluster)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(nats_watch_watcher_error_count{name=~\"${name}\"}[5m]))",
       "legendFormat": "Errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Alert Definitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Pings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nats_watch_statsz_server_response_count{}[1m])*60",
       "legendFormat": "{{server}} -> {{name}}"
      },
      {
       "expr": "rate(nats_watch_statsz_requests_count{}[1m])*60",
       "legendFormat": "{{name}} Requests"
      }
     ]
    },
    {
     "title": "Gossip Responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "rate(nats_watch_gossip_received_delay_count[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gossip Delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "rate(nats_watch_gossip_received_delay_sum[1m]) \n/\nrate(nats_watch_gossip_received_delay_count[1m]) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Watcher Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "increase(nats_watch_watcher_error_count[10m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}